# Generated by Django 5.1.7 on 2025-03-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('data_nascita', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indirizzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(max_length=255)),
                ('città', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=100)),
                ('stato', models.CharField(max_length=100)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo', to='vendita_libri.autore')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pubblicazione', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libri', to='vendita_libri.autore')),
            ],
        ),
    ]
