# Generated by Django 5.1.7 on 2025-03-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita_libri', '0002_utente'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='quantita',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
