# Generated by Django 5.1.7 on 2025-03-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita_libri', '0003_libro_quantita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autore',
            name='bio',
        ),
        migrations.AlterField(
            model_name='indirizzo',
            name='autore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo', to='vendita_libri.autore'),
        ),
    ]
