# Generated by Django 5.1.7 on 2025-03-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendita_libri', '0004_remove_autore_bio_alter_indirizzo_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='indirizzo',
            name='nazionalita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
